apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: sock-shop
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8079
      name: http
  selector:
    name: front-end