apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: chaos-engineering-cluster
  region: us-west-2

managedNodeGroups:
  - name: workers-1
    labels: { role: workers }
    instanceType: t3.micro
    desiredCapacity: 3
    volumeSize: 30
    privateNetworking: true