apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: chaos-engineering-cluster
  region: us-west-2

managedNodeGroups:
  - name: workers-1
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 4
    volumeSize: 30
    privateNetworking: true

  - name: monitoring
    labels: { 
      role: monitoring
    }
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 30
    privateNetworking: true

